{% set version = "1.1.1" %}
{% set name = "untangle" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e7cfa1ad57707e6b74cfea8b9fc50f7cbe9bbaf18401cc9d72192002bcd80bcb

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - untangle

about:
  home: https://github.com/stchris/untangle
  license: MIT
  license_file: 'LICENSE'
  summary: 'Convert XML documents into Python objects.'
  doc_url: https://untangle.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - htenkanen
